### Find user by ID
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "hammedashiru89@gmail.co",
  "password": "asdlfkajsd"
}


### Find User by Email
GET http://localhost:3000/auth?email=hammedashiru89@gmail.co
content-type: application/json
